### ISSUE TITLE
Installation fails on linux/arm64

### ISSUE THREAD

**Issue by bkline** [uswds/uswds-compile#25]
Running `npm install @uswds/compile --save-dev` as instructed by the [documentation](https://designsystem.digital.gov/documentation/getting-started/developers/phase-two-compile/) fails with the error message
```
Unexpected platform or architecture: linux/arm64
```

![image](https://user-images.githubusercontent.com/1634628/163402896-4d98a3c0-0091-4265-a328-17d2fb389ba0.png)

Ignoring all the deprecation warnings, is there a path which works around this failure (skipping the extra bells and whistles this package is trying to pull in) enabling the use of `sass` to compile the `.scss` files, or is the only alternative to use the pre-compiled CSS version of USWDS?

**Comment by bkline** [comment]
I'm hoping there a middle path here, based on the language in the _What You Need_ section. of the [Getting started for developers](https://designsystem.digital.gov/documentation/getting-started-for-developers/) page, which implies that all that is needed is
- `node`
- `npm`
- `sass`
I just didn't see any details for how to set up a minimum development environment.

**Comment by mejiaj** [comment]
@bkline I thought node support in general was limited in ARM devices.

Would you mind giving us a little more information? What version of node and what Linux distribution are you using?

**Comment by bkline** [comment]
@mejiaj This is in a `Dockerfile` based on the `ubuntu:jammy` image. Here's the relevant portion:

```
ENV NVM_DIR /usr/local
ENV NODE_VERSION 16.14.2
RUN curl --silent -o- \
    https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
RUN . $NVM_DIR/nvm.sh && \
    nvm install $NODE_VERSION && \
    nvm alias default $NODE_VERSION && \
    nvm use default
RUN npm install -g npm@8.6.0
```
Using the most recent version of `node` as instructed in the [documentation](https://designsystem.digital.gov/documentation/getting-started/developers/phase-one-install/).

**Comment by bkline** [comment]
> I thought node support in general was limited in ARM devices.

It's not `node`. That part's OK. The problem is that the only documented path to getting the pieces in place for compiling the stylesheets has a dependency on getting a bunch of other things installed. The dependency that tripped up the installer was `PhantomJS`. In a perfect world it would be nice to have all those other tools, but they're not all necessary for the basic task of compiling the .scss files. That's why I was asking above if there's documentation squirreled away somewhere for a workaround which would get what's _really_ needed for that task set up while the installation dependency failure is being addressed.

**Comment by mgwalker** [comment]
USWDS and this compile utility both rely on [`gulp-svg-sprite`](https://npm.im/gulp-svg-sprite) to stitch SVGs together into a sprite sheet. That library has a downstream dependency on PhantomJS which has been deprecated for 4 years. The dependency tree is something like this:

```
@uswds/compile
|____ gulp-svg-sprite@1.5.0
    |____ svg-sprite@1.5.4
        |___ phantomjs-prebulit@2.5.4 - uses or downloads prebuilt PhantomJS
```

There are no versions of the intermediary dependencies that ***don't*** ultimately rely on PhantomJS. PhantomJS can probably be built on arm/64, but there's no *prebuilt* binary, and because the project is suspended, there likely won't ever be one. `phantomjs-prebuilt` will [use an existing PhantomJS](https://www.npmjs.com/package/phantomjs-prebuilt#using-phantomjs-from-disk) if it finds one of the same version that it expects, so it might be possible to jump through some hoops to manually build it in your arm/64 environment and let `phantomjs-prebuilt` find that. Note that even when the project was actively supported, the maintainers [discouraged people from building from source](https://phantomjs.org/build.html), but maybe you don't really have another choice.

Ideally USWDS (which itself also depends on `gulp-svg-sprite`) and this compile helper would migrate to a gulp plugin that doesn't rely on PhantomJS, but until then, it's a significant burden to build USWDS on arm/64 architectures.

(This is not a dunk on USWDS. `svg-sprite` uses a browser rendering environment to [accurately measure the dimensions](https://github.com/svg-sprite/svg-sprite/issues/154#issuecomment-230152691) of source SVGs, since SVGs themselves are unreliable when it comes to their sizes. Whether or not that's applicable to USWDS, I don't know, but whatever would replace `gulp-svg-sprite` would probably also need some way of understanding the true rendered size of SVGs in order to resize them properly onto the sprite sheet.)

**Comment by mejiaj** [comment]
@mgwalker @bkline I've tested installing and running on a M1 Macbook air without any issues. But will continue to try to reproduce.

**Specs**
macOS Monterey v12.3.1
Macbook Air (M1, 2020)
node v16.14.2

**Comment by bkline** [comment]
@mejiaj Did you tell Docker to emulate the amd64 platform? If not, this is good news.

**Comment by mejiaj** [comment]
This was in OSX, not Docker sorry. 

It's in response to a slack message about Apple ARM64 chips and getting uswds/compile building.

**Comment by bkline** [comment]
👍
