### ISSUE TITLE
Should paths.src.projectSass be used in buildSass?

### ISSUE THREAD

**Issue by smustgrave** [uswds/uswds-compile#38]
I setup my new repo with 

uswds.paths.dist.fonts = './assets/fonts';
uswds.paths.dist.img = './assets/img';
uswds.paths.dist.js = './assets/js';
uswds.paths.dist.theme = './components/00-uswds';

uswds.paths.src.projectIcons = './images/**';

uswds.paths.src.projectSass = './components';

I want the sass files outputted to 00-uswds just once during init (per the recommendation) then when I build I want everything to compile in our components folder.  but it appears to only look at 00-uswds.

I had to change the variable post init for it to work.

**Comment by mahoneycm** [comment]
Hey there Stephen,

Uswds-compile uses a single Sass entry point, which is defined with `paths.dist.theme`. After you initialize using `npx gulp init`, you should load any project Sass files outside of the `paths.dist.theme` directory, into your entry point using `@forward`, `@use`, or `@import`. Your sass files will always compile based to your entry point (in your case, `components/00-uswds`).

`paths.src.projectSass` should be used to tell gulp and your `watchSass` task to watch for changes on the files you set, not to set a second sass output location. 

We recommend using `init` only once because it will overwrite project files, such as settings files and Sass entry points.

If you would in fact like a copy of your compiled sass output, you can include that as part of your custom build script

Please refer to the uswds-compile README for more information.

If this does not answer your question, please feel free to reach out with more details!

Thank you,
Charlie
